# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_change_username_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cui',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Código único de identificación CUI'),
        ),
        migrations.AddField(
            model_name='user',
            name='cui_verified',
            field=models.BooleanField(default=False, help_text="Indicates that this user's cui has been verified as being associated with the individual able to log in to this account.", verbose_name='CUI verificado'),
        ),
    ]
